### ISSUE TITLE
Code keeps not coming!  Why'd you say it was?

### ISSUE THREAD

**Issue by faddat** [hackpad/hackpad#1]
Problem:  Apps don't run without source code....

**Comment by frbayart** [comment]
Are you sure ?
[[selfie-placeholder-0]]

**Comment by shanukus98765** [comment]
This was announced about a month back. Mailed them multiple times, but did not receive any reply.

**Comment by dyyce** [comment]
was it announced before or after they got aquired?

**Comment by faddat** [comment]
....elaborate april fools' joke?

**Comment by fimdomeio** [comment]
sorry forgot to push the changes. done.


Alexandre Castro <http://www.fimdomeio.com>

**Comment by kiasaki** [comment]
Captain here!

![screen shot 2015-05-05 at 10 54 56 am](https://cloud.githubusercontent.com/assets/1158933/7475381/3ce046b2-f315-11e4-8efb-6e195fd21f6e.png)

*flies away*

**Comment by andytruong** [comment]
May (:

**Comment by jimmybrancaccio** [comment]
I really want to get in on this too. I hope they toss up some code soon!

**Comment by joelbeckham** [comment]
Can't wait for it show up.

**Comment by akshat-g** [comment]
The worse part is they are not even replying back to mails and twitter messages. We can all just guess what 'few weeks' mean to them. It has already been 5 weeks from announcement.

**Comment by terrencestark** [comment]
Maybe  hackpad team don't have enough right to release the source code since dorpbox acquired them.

從我的 Windows Phone 寄出
________________________________

**Comment by faddat** [comment]
We can hope otherwise.... Would have been a very cool addition to the
ecosystem!

**Comment by uzi200** [comment]
Maybe they are refactoring the code. Hmm..

**Comment by captn3m0** [comment]
It has been more than a month since the announcement. They should have delayed the announcement or said "few months" instead of the "few weeks" that was promised.

**Comment by taherali** [comment]
At least they should have courtesy to reply back for mails and tweets if the process is delayed.

**Comment by igorkofman** [comment]
Hi guys.  Sorry about the delay.  We're working on preparing the release and will have an update early next week.  Thanks for your patience!!

**Comment by jimmybrancaccio** [comment]
Good to see an update! Thanks @igorkofman! :+1:

**Comment by faddat** [comment]
Cool!  I'm thrilled to hear it!

**Comment by shanukus98765** [comment]
@igorkofman: any updates from Hackpad regarding the release?

**Comment by saddington** [comment]
+1... love to know!

**Comment by taherali** [comment]
+1 hoping to hear about this soon its been more than a week @igorkofman

**Comment by thedangler** [comment]
WTF?

**Comment by aapris** [comment]
I'm a bit disappointed, still waiting for the source. 
See Open source anti-pattern: no source! (slide 10):
http://www.slideshare.net/bcantrill/corporate-open-source-antipatterns

Still hopeful though. :)

**Comment by faddat** [comment]
Just read that presentation yesterday.  Certainly did think of this
situation....

Jacob Gadikian
E-mail: faddat@gmail.com
SKYPE: faddat
Phone/SMS: +86 186-2612-6079

**Comment by lra** [comment]
any news?

**Comment by captn3m0** [comment]
- The announcement was made [52 days ago](https://news.ycombinator.com/item?id=9352249)
- we are approaching 3 weeks since the last update.

I am fine with the release getting delayed, but I just wish that they gave us updates or realistic schedules.

**Comment by PaulNendick** [comment]
C'mon Hackpad, don't fall into the [open source anti-pattern](https://modelviewculture.com/pieces/what-your-open-source-culture-really-says-part-one)!

**Comment by almereyda** [comment]
A long week, indeed.

**Comment by pierreozoux** [comment]
I think "no source" is the worst open source anti pattern!

**Comment by faddat** [comment]
We're all here because we like your app, and want to work on it with you.  Any chance you might enable that any time soon?

**Comment by michalzacher** [comment]
An update would be really helpful indeed...

**Comment by joelbeckham** [comment]
I wonder if they're waiting for [dropbox notes](https://notes.dropbox.com/) to come out of private beta or something.

**Comment by jimmybrancaccio** [comment]
@joelbeckham That's interesting. I'd never heard of Dropbox Notes until today!

**Comment by joelbeckham** [comment]
@jimmybrancaccio Dropbox aquiared Hackpad a while ago, and it seems like Notes is the outcome of that. It kinda seemed to me that Hackpad was opensourcing their code to be kind to the community before completely moving on to Notes. We'll see.

http://www.pcmag.com/article2/0,2817,2480359,00.asp

**Comment by jimmybrancaccio** [comment]
@joelbeckham I did know about the acquire, but I didn't know Dropbox had or was in the process of developing their own notes system (not sure why that didn't click since they got Hackpad, thought they might leave them separate, though now that I think about it, that doesn't make sense hah). The screenshot on the Dropbox Notes page looks familiar to Hackpad now that I look at it.

At this point I wouldn't be surprised if they _didn't_ open source Hackpad.

**Comment by wolftune** [comment]
This is why you should use the GPL folks. Hackpad itself is just a fork of Etherpad, but we don't get source for the fork because Etherpad uses a permissive license even though it's open source itself.

**Comment by AceChenX** [comment]
I sent support@hackpad.com an Email to ask about the open source, the following is their reply.
![untitled](https://cloud.githubusercontent.com/assets/2907374/8223011/98bcc656-15a5-11e5-9542-eac7394fa338.png)

**Comment by l1x** [comment]
This is the most perfect code I have ever seen in my entire life. It is not buggy, it does what it supposed to, and it is correct, no doubt of that. I don't see why people are complaining....

**Comment by philsnow** [comment]
@wolftune You mean LGPL?  GPL doesn't obligate anybody to do all that much unless they're _distributing_ software.

(completely ignoring the normative statement that people "should" use this or that license)

**Comment by xorgy** [comment]
@philsnow It would apply to the client side, as they are distributing that.

**Comment by saddington** [comment]
ROFL @l1x... ROFL.

**Comment by ericvicenti** [comment]
We should remind ourselves that we're not entitled to anything more than an empty repo. Cleaning up code for open source consumption is a lot of work, and to be honest, it doesn't pay well at all. I don't blame them for taking their time.

@wolftune, you really think the license is the reason we don't have the hackpad source right now? If etherpad was (L)GPL, the hackpad creators would not have forked it, because they were trying to create a proprietary service. The product might not exist at all, or they would have started from something else.

If you're thinking about the license for your project, choose a more permissive license if you want explosive growth. Otherwise people will think twice about adopting it at their company.

**Comment by wolftune** [comment]
@philsnow — you're right and wrong (and I was careless). I *meant* AGPL. (LGPL would be less strong than even GPL).

@ericvicenti if etherpad was AGPL, it would have blocked hackpad from being proprietary. If that meant it wouldn't exist, then great — that would have resulted in *more* adoption and contribution to etherpad. Hackpad was a product that took users away from Etherpad by being an improved fork. Blocking such proprietary derivatives would be good for software freedom. It might also have blocked Dropbox's new thing that may be based on Etherpad too for all I know, and that too could be positive.

On the other hand, Hackpad could have chosen to make their product anyway and still provide their service and it *could* have worked and would have benefited from Open Source contributions etc. So who knows, it's just speculation.

Anyway, we're not entitled to Hackpad source, but Hackpad shouldn't have been entitled to Etherpad's source… I do hope they follow through on the release.

**Comment by rkettering** [comment]
**@wolftune** –
You know, I'd like this to become a meme...  the GPL sucks because in order to believe it does any good, you have to believe in "legalism" - a fallacy that geeks like us are painfully susceptible to.  **Legalism does not work in the real world.**

It's the fallacy that if something is illegal, that being illegal **has stopping power** - that its some sort of unstoppable force that compels 'most', rather than 'some' people.  It's almost a sort of magical thinking - that if we just manage to make something "officially against the rules", it'll rewrite the Old Magic of the world and stop everyone from doing it, ever.  We forget that "illegality as impediment" is a sliding scale; that it's power waxes and wanes with the infraction.  Even against heinous crimes like murder and sex crimes, being illegal is surprisingly weak, and against things most people don't care about, it's a joke (music piracy, or drug prohibition, or any rules against different kinds of sex).

It's *especially* not an impediment when it's something like software licensing where we barely have the money to buy lawyers (the EFF really has to pick its battles carefully), where the juries and judges struggle to understand what the free software movement even is, where people don't believe we're some "too big to fail" organization that an abiding cultural asset that provides tons of jobs, and where by the time we'd finished the court case, the company stealing the software would have already disposed of the stolen code they used to bootstrap themselves and would have enough money to laugh at any judgement passed against them (or would have already flipped themselves as a startup).

` `

It doesn't work.  And compared to permissive licenses, which have almost no downsides, the GPL has a bunch of downsides; it's really restrictive of your freedoms about who can use your stuff, and what you can accept into your work (which is really darkly ironic), and it's toxic to culture because of the inherent hypocrisy, doublethink, and denial-of-reality it brings out of the woodwork - like any cult.

After years of personal involvement, I've lost my religion for the GPL, and you should too.  It's bad for us as a free-software movement.  We need to stop door-to-door GPL preachers every time they show up and say that ~~Jesus~~ the GPL would have solved all your problems.

Join the anti-gpl movement.  Let's put this thing out of its misery.

**Comment by wolftune** [comment]
@rkettering Now you're really pushing this off-topic. I made it a tangent (sorry). This discussion doesn't belong here. Your post is utter hyperbole and has nothing but abstract dogma anyway. I'm not saying my point was totally different, but you've just presented an opposing side to an argument in which both sides were purely rhetorical while boldly claiming your side to be the practical one.

Put simply: in *practice*, the GPL is violated sometimes, enforced sometimes, respected sometimes, disrespected sometimes, useful sometimes, controversial sometimes, etc. etc. Your viewpoint here is as dogmatic and extremist and religious as any I've ever seen. I'm not going to spend any further time discussing with someone taking a totally dogmatic view of something based entirely on abstract rhetoric instead of cited evidence about reality while claiming to be the side of practical realism. If you want to understand the *practical* importance of GPL (such as for the Linux kernel), that's a topic worth actually discussing, but not here where we have truly strayed too far from talking about HackPad.

**Comment by socceroos** [comment]
@rkettering 
    it's really restrictive of your freedoms about who can use your stuff, and what you can accept into your work (which is really darkly ironic), and it's toxic to culture because of the inherent hypocrisy, doublethink, and denial-of-reality it brings out of the woodwork - like any cult.

You were going well until you spouted this rubbish. Stop pretending the world is built and run on anarchy. It's not. The pathetic notion that GPL is a 'denial-of-reality' belies your misunderstanding of the cause at it's core.

Otherwise, your comment has some good points.

**Comment by claudioruiz** [comment]
Whatever.
Please release the code.

**Comment by zomux** [comment]
Code!

**Comment by schlos** [comment]
+1

**Comment by fimdomeio** [comment]
+1

**Comment by xetch** [comment]
+1

**Comment by julianadenauer** [comment]
+1

**Comment by LeeroyDing** [comment]
Perhaps you should delete this repo instead.

**Comment by almereyda** [comment]
Yes, this could be less embarrassing. All this conversation could be moved
to `/dev/null` and they could think about their announcement pipeline from
scratch.

**Comment by pierreozoux** [comment]
+1 for `git mv https://github.com/hackpad/hackpad /dev/null`.

Like this, we know where to find it!

**Comment by faddat** [comment]
In the spirit of inclusiveness, I'm gonna hope it comes out they had a damn
good reason-- however, I cannot fathom what a damn good reason for this
might be.

Jacob Gadikian
E-mail: faddat@gmail.com
SKYPE: faddat
Phone/SMS: +84 167 789 6421

**Comment by captn3m0** [comment]
@joelbeckham [above](https://github.com/hackpad/hackpad/issues/1#issuecomment-112206383)

>I wonder if they're waiting for [dropbox notes](https://notes.dropbox.com/) to come out of private beta or something.

**Comment by ds0nt** [comment]
https://github.com/hackpad/hackpad/issues/6 <-- this

**Comment by lra** [comment]
BEGIN OFFTOPIC

> #6 <-- this

Anybody can create a repo, it's just noise until there is actually some source code to start collaboratively working on it

END OFFTOPIC

**Comment by faddat** [comment]
You're right @ira.  we're working on it.  Let me tell you what we're working on specifically-- now of course this is an @ds0nt + github community joint-- Im backup on this but as I understand it, we're going to start with gobby as a base, give it a better-looking UI, and after that, maybe rewrite the whole thing in Go?  

I have no problem with your challenge of the project's legitimacy or viability until we drop code into the waiting arms of people who like real-time collaboration.  It's only fair, now isn't it?

:)

**Comment by almereyda** [comment]
Did anybody write to `hackpad-oss@dropbox.com`, yet?

**Comment by captn3m0** [comment]
Thinking of setting up `ishackpadopensourcedyet.com`.

I wrote to them recently (>1 week or so), and still no response.

**Comment by faddat** [comment]
I gotta say I started this as a little riff at them mostly because I wanted
to play with their tech.

But dudes, why "go open source" if that's not your intention or desire?

**Comment by captn3m0** [comment]
http://ishackpadfossyet.com/ is live

**Comment by reality** [comment]
<crickets>

**Comment by thomasince** [comment]
Very disappointing that they have not released it yet.

Its like

Dropbox:  "do you want a cookie"?
Internet: "Hell yes"

Dropbox: "great, you can't have one"

**Comment by fimdomeio** [comment]
I think that at this point we should all assume that some members of the hackpad team knew they were going to be fired by dropbox coming week, and that hackpad was going to die forever, so they used all the power they had left to release the newsletter and create the repo, but at that point a alien spaceship took them, froze them, and left them in a pyramid in the middle of Amazonia.

**Comment by thomasince** [comment]
Dropbox should at least come clean and apologize.

I'm going to cancel my Dropbox account.

**Comment by jimmybrancaccio** [comment]
That seems a bit much but whatever floats your boat! :stuck_out_tongue_closed_eyes:

**Comment by igorkofman** [comment]
-- 

Thanks for your interest in the Hackpad Open Source release. We are excited to announce that the code is now available on GitHub at:

https://github.com/dropbox/hackpad

Hackpad began as an offshoot of an open source project (Etherpad), and we’ve always been committed to bringing it full circle and making the codebase available to the developer community. 

We’re excited to make it available today and can’t wait to see what you all do with it!

The Hackpad Team

**Comment by fimdomeio** [comment]
Yeaaaahh! Thank you very much dear

**Comment by saddington** [comment]
Wait... WHAH?!?

**Comment by jimmybrancaccio** [comment]
Yay! Very cool! :+1:

**Comment by thomasince** [comment]
Thanks Dropbox!

**Comment by lra** [comment]
@igorkofman  do you plan to accept and merge pull requests? or is it mainly readonly and supposed to be forked.

**Comment by dandv** [comment]
I wasted a good few minutes reading this entire thread, only to find out in comment #100 that the code was released in a different repo.

@igorkofman: how about creating a quick README.md to point to [that repo](https://github.com/dropbox/hackpad)?

**Comment by captn3m0** [comment]
@faddat Would be cool if you could mark this issue as closed.

**Comment by faddat** [comment]
Thank you guys!

**Comment by faddat** [comment]
Have been meaning to close this.  Thanks to the @hackpad / @dropbox team for opening your source code for the world to ab(use)!
